[tool.poetry]
name = "deepgis-utils"
version = "0.1.0"
description = ""
authors = ["Xuanh.W <Xuanhao.W.coding@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
